// const BACK_URL = "http://127.0.0.1:5000";
const BACK_URL = "https://curate-cornell-9e700cd2e9e3.herokuapp.com";
export const UPLOAD_URL = `${BACK_URL}/upload`;
export const INIT_URL = `${BACK_URL}/init`;
export const OVERVIEW_URL = `${BACK_URL}/patient/overview`;
export const DOCUMENTS_URL = `${BACK_URL}/patient/documents`;
export const DOCUMENT_URL = `${BACK_URL}/patient/document/`;
export const DOC_SUM_URL = `${BACK_URL}/patient/document_summary/`;
export const QUERY_URL = `${BACK_URL}/patient/query`;
